// mock de produtos
const API_BASE_URL = window.API_BASE_URL;
const mockProducts = [
  {
    id: 1,
    name: "Kofi",
    category: "Single Origin",
    price: 65.99,
    description: "Café de origem única com notas florais e acidez equilibrada. Cultivado nas montanhas da Etiópia, este café oferece uma experiência sensorial única com aromas frutados e sabor marcante. Ideal para métodos de preparo que realcem suas características especiais. Pacote de 250g.",
    imageUrl: "imagens/01.jpg",
  },
  {
    id: 2,
    name: "Superb",
    category: "Specialty Coffee",
    price: 50.9,
    description: "Café especial com perfil complexo e sabor excepcional. Selecionado cuidadosamente pelos nossos especialistas, apresenta notas de chocolate e caramelo com final doce e prolongado. Perfeito para apreciadores de cafés premium. Pacote de 250g.",
    imageUrl: "imagens/02.jpg",
  },
  {
    id: 3,
    name: "Kafeega",
    category: "Orgânico",
    price: 45.0,
    description: "Café orgânico certificado, cultivado sem agrotóxicos em fazendas sustentáveis. Sabor suave e equilibrado com notas terrosas e levemente adocicadas. Uma escolha consciente para quem valoriza qualidade e responsabilidade ambiental. Pacote de 250g.",
    imageUrl: "imagens/03.jpg",
  },
  {
    id: 4,
    name: "Grão Divino",
    category: "Specialty Coffee",
    price: 58.0,
    description: "Café especial de alta qualidade com sabor divino e aroma intenso. Torrado artesanalmente para realçar suas características únicas. Apresenta notas de frutas vermelhas e chocolate amargo com acidez vibrante. Pacote de 250g.",
    imageUrl: "imagens/04.jpg",
  },
  {
    id: 5,
    name: "Don Superior",
    category: "Single Origin",
    price: 72.5,
    description: "Café premium de origem única das montanhas colombianas. Sabor superior com notas de caramelo, especiarias e final persistente. Cultivado em altitude elevada, oferece uma experiência de degustação incomparável. Pacote de 250g.",
    imageUrl: "imagens/05.jpg",
  },
  {
    id: 6,
    name: "La Première",
    category: "Microlote",
    price: 67.99,
    description: "Microlote exclusivo de café premium com características excepcionais. Produzido em pequenas quantidades para garantir qualidade máxima. Sabor complexo com notas florais, frutadas e acidez delicada. Uma verdadeira joia para conhecedores. Pacote de 250g.",
    imageUrl: "imagens/06.jpg",
  },
  {
    id: 7,
    name: "Caffè",
    category: "Orgânico",
    price: 55.99,
    description: "Café orgânico italiano com tradição e sabor autêntico. Blend especial de grãos selecionados, torrado segundo métodos tradicionais. Sabor encorpado com notas de castanhas e chocolate, ideal para espresso. Pacote de 250g.",
    imageUrl: "imagens/07.jpg",
  },
  {
    id: 8,
    name: "Matiz",
    category: "Blend",
    price: 32.0,
    description: "Blend harmonioso que combina diferentes origens para criar um sabor único e equilibrado. Notas de chocolate ao leite e caramelo com acidez suave. Perfeito para o consumo diário e todos os métodos de preparo. Pacote de 250g.",
    imageUrl: "imagens/08.jpg",
  },
  {
    id: 9,
    name: "Gud Coffee",
    category: "Single Origin",
    price: 57.99,
    description: "Café de origem única com sabor excepcional e características distintivas. Cultivado em condições ideais, apresenta notas de frutas tropicais e mel com acidez brilhante. Uma experiência única para paladares exigentes. Pacote de 250g.",
    imageUrl: "imagens/09.jpg",
  },
  {
    id: 10,
    name: "Kava",
    category: "Varietal",
    price: 47.99,
    description: "Varietal especial com características únicas da variedade cultivada. Sabor distintivo com notas herbais e terrosas, acidez moderada e corpo médio. Ideal para quem busca experiências diferenciadas no café. Pacote de 250g.",
    imageUrl: "imagens/10.jpg",
  },
  {
    id: 11,
    name: "Kafea Lat",
    category: "Orgânico",
    price: 57.99,
    description: "Café orgânico de cultivo sustentável com sabor rico e complexo. Notas de chocolate escuro e especiarias com final prolongado. Certificação orgânica garante qualidade e responsabilidade ambiental. Pacote de 250g.",
    imageUrl: "imagens/11.jpg",
  },
  {
    id: 12,
    name: "Kafe",
    category: "Microlote",
    price: 49.99,
    description: "Microlote especial produzido em pequenas quantidades para máxima qualidade. Sabor refinado com notas de frutas vermelhas e acidez vibrante. Cada lote é único e oferece uma experiência sensorial excepcional. Pacote de 250g.",
    imageUrl: "imagens/12.jpg",
  },
  {
    id: 13,
    name: "Aurora",
    category: "Varietal",
    price: 33.99,
    description: "Varietal Aurora com sabor suave e delicado como o nascer do sol. Características florais e frutadas com acidez refrescante. Ideal para quem aprecia cafés mais leves e aromáticos. Excelente para métodos filtrados. Pacote de 250g.",
    imageUrl: "imagens/13.jpg",
  },
  {
    id: 14,
    name: "Royale",
    category: "Blend",
    price: 44.99,
    description: "Blend real que combina nobreza e tradição em cada gole. Sabor equilibrado com notas de caramelo e chocolate ao leite. Corpo médio e acidez suave, perfeito para todas as ocasiões. Uma escolha elegante e refinada. Pacote de 250g.",
    imageUrl: "imagens/14.jpg",
  },
  {
    id: 15,
    name: "Velvet Brew",
    category: "Blend",
    price: 59.99,
    description: "Blend aveludado com textura sedosa e sabor envolvente. Combinação harmoniosa de grãos premium resulta em notas de baunilha e amêndoas. Experiência sensorial única com final prolongado e satisfatório. Pacote de 250g.",
    imageUrl: "imagens/15.jpg",
  },
  {
    id: 16,
    name: "Summit",
    category: "Specialty Coffee",
    price: 52.99,
    description: "Café especial que representa o ápice da qualidade e sabor. Cultivado em grandes altitudes, oferece complexidade e intensidade excepcionais. Notas de chocolate escuro e especiarias com acidez marcante. Pacote de 250g.",
    imageUrl: "imagens/16.jpg",
  },
  {
    id: 17,
    name: "Château Noir",
    category: "Microlote",
    price: 47.99,
    description: "Microlote elegante e sofisticado como um château francês. Sabor complexo com notas de frutas escuras e toques de carvalho. Produção limitada garante exclusividade e qualidade superior. Uma experiência gastronômica única. Pacote de 250g.",
    imageUrl: "imagens/17.jpg",
  },
  {
    id: 18,
    name: "L'Élixir",
    category: "Varietal",
    price: 60.99,
    description: "Varietal especial que é como um elixir mágico para os sentidos. Sabor intenso e aromático com notas de especiarias exóticas e frutas tropicais. Cultivado com técnicas especiais para realçar suas qualidades únicas. Pacote de 250g.",
    imageUrl: "imagens/18.jpg",
  },
];

export { mockProducts };
