// mock de produtos
const API_BASE_URL = window.API_BASE_URL;
const mockProducts = [
  {
    id: "prod001",
    name: "Kofi",
    category: "Single Origin",
    price: 65.99,
    description: "250g..",
    imageUrl: "imagens/01.jpg",
  },
  {
    id: "prod002",
    name: "Superb",
    category: "Specialty Coffee",
    price: 50.9,
    description: "250g..",
    imageUrl: "imagens/02.jpg",
  },
  {
    id: "prod003",
    name: "Kafeega",
    category: "Orgânico",
    price: 45.0,
    description: "250g",
    imageUrl: "imagens/03.jpg",
  },
  {
    id: "prod004",
    name: "Grão Divino",
    category: "Specialty Coffee",
    price: 58.0,
    description: "250g",
    imageUrl: "imagens/04.jpg",
  },
  {
    id: "prod005",
    name: "Don Superior",
    category: "Single Origin",
    price: 72.5,
    description: "250g",
    imageUrl: "imagens/05.jpg",
  },
  {
    id: "prod006",
    name: "La Première",
    category: "Microlote",
    price: 67.99,
    description: "250g",
    imageUrl: "imagens/06.jpg",
  },
  {
    id: "prod007",
    name: "Caffè",
    category: "Orgânico",
    price: 55.99,
    description: "250g",
    imageUrl: "imagens/07.jpg",
  },
  {
    id: "prod008",
    name: "Matiz",
    category: "Blend",
    price: 32.0,
    description: "250g",
    imageUrl: "imagens/08.jpg",
  },
  {
    id: "prod009",
    name: "Gud Coffee",
    category: "Single Origin",
    price: 57.99,
    description: "250g",
    imageUrl: "imagens/09.jpg",
  },
  {
    id: "prod010",
    name: "Kava",
    category: "Varietal",
    price: 47.99,
    description: "250g",
    imageUrl: "imagens/10.jpg",
  },
  {
    id: "prod011",
    name: "Kafea Lat",
    category: "Orgânico",
    price: 57.99,
    description: "250g",
    imageUrl: "imagens/11.jpg",
  },
  {
    id: "prod012",
    name: "Kafe",
    category: "Microlote",
    price: 49.99,
    description: "250g",
    imageUrl: "imagens/12.jpg",
  },
  {
    id: "prod013",
    name: "Aurora",
    category: "Varietal",
    price: 33.99,
    description: "250g",
    imageUrl: "imagens/13.jpg",
  },
  {
    id: "prod014",
    name: "Royale",
    category: "Blend",
    price: 44.99,
    description: "250g",
    imageUrl: "imagens/14.jpg",
  },
  {
    id: "prod015",
    name: "Velvet Brew",
    category: "Blend",
    price: 59.99,
    description: "250g",
    imageUrl: "imagens/15.jpg",
  },
  {
    id: "prod016",
    name: "Summit",
    category: "Specialty Coffee",
    price: 52.99,
    description: "250g",
    imageUrl: "imagens/16.jpg",
  },
  {
    id: "prod017",
    name: "Château Noir",
    category: "Microlote",
    price: 47.99,
    description: "250g",
    imageUrl: "imagens/17.jpg",
  },
  {
    id: "prod018",
    name: "L'Élixir",
    category: "Varietal",
    price: 60.99,
    description: "250g",
    imageUrl: "imagens/18.jpg",
  },
];

export { mockProducts };
