services:
  - type: web
    name: cafelier
    runtime: node
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    pullRequestPreviewsEnabled: true
